services:
  GlobeGroup\NotifierBundle\Sender\EmailLabs: ~
  GlobeGroup\NotifierBundle\Sender\SMSLabs: ~
  GlobeGroup\NotifierBundle\Service\NotificationSendService:
    arguments:
      - '@GlobeGroup\NotifierBundle\Sender\SMSLabs'
      - '@GlobeGroup\NotifierBundle\Sender\EmailLabs'
      - '%kernel.cache_dir%'
      - '%env(NOTIFIER_CACHE_DIR)%'
  GlobeGroup\NotifierBundle\EventListener\ExceptionListener:
    arguments:
      - '@GlobeGroup\NotifierBundle\Service\NotificationSendService'
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }
  GlobeGroup\NotifierBundle\Command\ResetExceptionCommand:
    arguments:
      - '@GlobeGroup\NotifierBundle\Service\NotificationSendService'
    tags:
      - { name: 'console.command', command: 'notifier:remove-lock' }
